# These are supported funding model platforms

github: [NOTREGRETO]
patreon: 
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
otechie: 
buy_me_coffee: ['https://www.buymeacoffee.com/NOTREGRETO']
